# Generated by Django 5.1 on 2024-08-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_course_options_alter_coursemodul_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
