# Generated by Django 5.1 on 2024-08-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_api_course_id_fc19fc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcomment',
            name='listing',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
